import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from './components/Navbar';
import Footer from './components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' data-theme='light'>
      <body className={inter.className}>
        <main className='max-w-7xl mx-auto min-h-screen relative'>
          <Navbar />
          {/* <div className='divider'></div> */}
          {children}
          {/* <Footer /> */}
        </main>
      </body>
    </html>
  );
}
